name: pgm
channels:
  - pyg
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - pycparser=2.21
  - pyg=2.0.4
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-louvain=0.15
  - pytorch=1.11.0
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.14
  - pytorch-spline-conv=1.2.1
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.3
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.6
  - yacs=0.1.6
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.0.8
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - captum==0.2.0
    - cilog==1.2.3
    - cloudpickle==2.2.0
    - decorator==5.1.1
    - et-xmlfile==1.1.0
    - executing==1.1.1
    - filelock==3.8.0
    - gdown==4.5.1
    - h5py==3.7.0
    - hydra-core==1.2.0
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipython==8.5.0
    - jedi==0.18.1
    - llvmlite==0.39.1
    - matplotlib-inline==0.1.6
    - mpmath==1.2.1
    - munch==2.5.0
    - mypy-extensions==0.4.3
    - numba==0.56.2
    - omegaconf==2.2.3
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - pgmpy==0.1.20
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.31
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.13.0
    - pyscf==1.7.6.post1
    - rdkit==2022.3.5
    - rdkit-pypi==2022.3.5
    - setuptools==59.8.0
    - shap==0.41.0
    - slicer==0.0.7
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - statsmodels==0.13.2
    - sympy==1.11.1
    - tabulate==0.9.0
    - traitlets==5.4.0
    - typed-argument-parser==1.7.2
    - typing-inspect==0.8.0
    - wcwidth==0.2.5
    - zipp==3.9.0
